# Generated by Django 5.1.1 on 2024-09-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='instructions',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='mealType',
            field=models.JSONField(),
        ),
    ]
