# Generated by Django 5.1.1 on 2024-09-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_recipes_ingredients_alter_recipes_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.JSONField()),
                ('instructions', models.JSONField()),
                ('image', models.TextField()),
                ('mealType', models.JSONField()),
                ('rating', models.FloatField()),
                ('reviewCount', models.IntegerField()),
                ('prepTimeMinutes', models.IntegerField()),
                ('cookTimeMinutes', models.IntegerField()),
                ('caloriesPerServing', models.IntegerField()),
            ],
        ),
    ]
